# Generated by Django 4.2.2 on 2023-07-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_ratig_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratig',
            new_name='Rating',
        ),
        migrations.RenameModel(
            old_name='Revie',
            new_name='Reviews',
        ),
    ]
