# Generated by Django 4.2.2 on 2023-07-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_geners_movie_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='catagory',
            new_name='category',
        ),
    ]
