# Generated by Django 4.2.2 on 2023-07-21 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_catagory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actros',
            field=models.ManyToManyField(blank=True, related_name='film_actor', to='movies.actor', verbose_name='актеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='указывать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='film_director', to='movies.actor', verbose_name='режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_usa',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в США'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_world',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в мире'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.genre', verbose_name='жанры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='world_premier',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Премьера в мире'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023, verbose_name='Дата выхода'),
        ),
    ]
